### ISSUE TITLE
Wrong URL when inside an article

### ISSUE THREAD

**Issue by paulocoutinhox** [pelican-plugins/search#10]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/pelican-plugins/search/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

## Issue

Hi,

When enable search, the stork url is not going to correct place when im inside article:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/395096/182542440-6dc66c07-85e4-4658-a86e-7eac4102defd.png">

Example on screenshot above:
http://localhost:8000/2022/06/28/2022/06/28/apocalipse-de-jesus-cristo-fase-3-o-trono-e-os-seres-viventes.html

```
duplicated: 2022/06/28/2022/06/28
```

If im on home, it is working.

Thanks.

**Comment by justinmayer** [comment]
I believe I have fixed this problem. I will update this issue once a new version has been published containing that fix.

**Comment by paulocoutinhox** [comment]
Thanks @justinmayer 

Can you create a new release?

**Comment by justinmayer** [comment]
New release containing this fix has been published: https://github.com/pelican-plugins/search/releases/tag/1.0.1
