### ISSUE TITLE
Layout issues due to Stork progress bar

### ISSUE THREAD

**Issue by ndeville** [pelican-plugins/search#14]
- [X ] I have searched the [issues](https://github.com/pelican-plugins/search/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [ X] I have searched the documentation and believe that my question is not covered.

I have a couple layout issues with the Stork progress bar.

First it appears in the middle of the article (seemingly where the results box would end).

Second, more bothersome, blank space appears on the right side of my page, which impacts usability, especially on mobiles when swiping. 

Narrowed down the issue (deleting elements in DevTools until I found the culprit) to this div:  

``` html
<div class="stork-progress" style="width: 100%; opacity: 0;"></div>
```

which is not mine - it seemingly gets inserted by the plugin at build time, and I have not managed to override the inline style via external CSS. 

When `width: 0%` my layout issue disappears (because the progress bar does not have any space, ie is hidden).

Where/how can I change width to 0%, or deactivate the progress bar entirely (ie not have this div inserted)?
Perhaps better for a future version to define those inline styles in the external CSS?

**Comment by justinmayer** [comment]
Hi Nic. If you do a quick search on this repo (e.g., for `stork-progress`), you'll see that the line in question is not added by the plugin but by Stork itself. So you'd have to refer to Stork's documentation and discussion forum to see whether the customization you seek is possible. Sorry I couldn't provide more help! 😅
