### ISSUE TITLE
Just A Question: About Deploying A Pelican site with Search Enabled.

### ISSUE THREAD

**Issue by tas509** [pelican-plugins/search#28]
Hello,

I have just discovered Pelican and have a question about this search plugin.

To install the plugin, I also need to install Stork software... and it seems I need to install the mac version of the tool using brew. My hosting is on Linux, so if I add the plugin via pip ... surely that can't go any get a linux version of the app can it?  

(Or this is a .wasm thing, about which I know next to nothing, so it'll be compiled and served accordingly)

Sorry to be dense - but I won't have to go to my hosting and install a Linux version will I?  I'm looking for a super-simple search (I liked the look of the previous version of the plugin) for a site of <100 pages.... and would prefer the most basic option given that I may be teaching this approach to site building to students ... so it needs to be generic.

Thanks, I hope this makes some sense.

**Comment by justinmayer** [comment]
Using a static site generator has two components: the tool that generates the site (Pelican), and the web server that serves the static assets (Apache, Nginx, Caddy, etc.).

If you are using a Mac to run Pelican and generate the site, then you should install the Mac version of Stork. You do not need to install a Linux version of Stork if you are running a web server on Linux to serve the static assets.

By way of example, I use a Mac, Pelican, and the Mac version of Stork to generate the [Justin Mayer](https://justinmayer.com) web site. I followed the steps mentioned in the Search plugin README and then merely `rsync` the generated static assets to the Linux server, and the web server running on that Linux OS dutifully serves the static assets without any other Stork-related server-side configuration.

**Comment by tas509** [comment]
That answers all my questions beautifully, thank you.

**Comment by justinmayer** [comment]
Certainly! Glad I could be of help. 💫
