### ISSUE TITLE
How to translate stork?

### ISSUE THREAD

**Issue by paulocoutinhox** [pelican-plugins/search#9]
- [x] I have searched the [issues](https://github.com/pelican-plugins/search/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the documentation and believe that my question is not covered.

## Issue

How to translate search? My site is in portuguese and the search in english:

<img width="319" alt="image" src="https://user-images.githubusercontent.com/395096/182541104-f1dd686f-a1f7-43d9-a7eb-d9f2ce7af58f.png">

**Comment by paulocoutinhox** [comment]
I translate direct on JS file. This is the correct way?

**Comment by justinmayer** [comment]
If you are referring to the `124 files found` text, than I believe that comes directly from Stork and is outside the scope of what this plugin does. I suggest you search the existing [Stork discussion threads](https://github.com/jameslittle230/stork/discussions), and if you don't find anything about how to localize this text, then create a new discussion there asking about localization of Stork-provided text strings.

**Comment by paulocoutinhox** [comment]
Thanks, i edit it locally.
